### ISSUE TITLE
Key match errors in pre-trained SwinTransformer

### ISSUE THREAD

**Issue by qinghezeng** [Xiyue-Wang/TransPath#11]
Thank you so much for sharing the fantastic code and the pre-trained models!

I tired to use your code to load the weights for ctranspath and encounter the following error:
 `RuntimeError: Error(s) in loading state_dict for SwinTransformer:
	Missing key(s) in state_dict: "patch_embed.proj.weight", "patch_embed.proj.bias". 
	Unexpected key(s) in state_dict: "patch_embed.proj.0.weight", "patch_embed.proj.1.weight", "patch_embed.proj.1.bias", "patch_embed.proj.1.running_mean", "patch_embed.proj.1.running_var", "patch_embed.proj.1.num_batches_tracked", "patch_embed.proj.3.weight", "patch_embed.proj.4.weight", "patch_embed.proj.4.bias", "patch_embed.proj.4.running_mean", "patch_embed.proj.4.running_var", "patch_embed.proj.4.num_batches_tracked", "patch_embed.proj.6.weight", "patch_embed.proj.6.bias".`

Could you please kindly help me solve it? Many thanks in adcance!
Your sincerely,
Qinghe

**Comment by yangsenwxy** [comment]
Is your timm installed correctly? Ask us to provide the timm library.Other people use this is no problem pre-training is no problem

**Comment by Xiyue-Wang** [comment]
Is your timm installed correctly? Ask us to provide the timm library.Other people use this is no problem pre-training is no problem

**Comment by qinghezeng** [comment]
Thank you for your prompt reply! Indeed I didn't notice it need a modified version of timm library (my apologies for that!). After installing the correct timm, it worked well.
Just one more question, would this modified library affect the results of the MoCov3 models you provided? Thanks in advance!

**Comment by Xiyue-Wang** [comment]
It won't have any effect, but I recommend that you use ctranpath, this is the best, we have tested it, and the performance of other models is not as good as ctranspath

**Comment by qinghezeng** [comment]
Ok! Thank you so much for your kind sharing and advice!
