### ISSUE TITLE
CNN pretrained on all TCGA+PAIP

### ISSUE THREAD

**Issue by Dadatata-JZ** [Xiyue-Wang/TransPath#12]
Hi everyone! @Xiyue-Wang @Scu-sen  

I realize that one of my investigations that involve multi-center clinical data, may embrace your proposed architecture well. I am trying to add this into the paper at last minute and cite it. Before getting to the ViT, I would also like to check the baseline of CNN. Wondering whether you have ever tested pre-training CNN (maybe using MOCO or simclr) on the bulk dataset TCGA + PAIP as feature extractor? I saw the TransPath conference piece only compared pre-trained weights on imagenet. If there was CNN pretrained on the bulk histological images, can you share it to me for a quick test? 

...couldn't get your email contacts on the paper, otherwise I could tell you more about our work ; )  

Cheers,

**Comment by Xiyue-Wang** [comment]
I think this should also perform well. At present, CTransPath is performing very well. We have tested it many other tasks, and there will be concrete progress. Our extended paper is in major revison and will come soon. You can cite the extension In the paper, we compared the CNN pre-trained model, CTransPath is also the best performer, this model cost close to 400,000 US dollars in machine costs

**Comment by Xiyue-Wang** [comment]
my email is xiyue.wang.scu@gmail.com

**Comment by Dadatata-JZ** [comment]
> 
Thanks for the quick response. 
However, our downstream task is quite different since the specific diseases are different. Unfortunately, we couldn't simply fill up the digits into a table and form an ablation comparison like technical conference papers. Good performance with CtransPath is def important for us in the end but it would be hard to interpret to clinicians without tuning the same set with a CNN pretrained base.

There is no doubt about the capability of CTransPath surely, but it is simply not what we are looking for at this stage. Would your team be able to make the pre-trained CNN on TCGA+PAIP also available? It may be able to help spread your work widely. 

Thanks a bunch.

**Comment by Xiyue-Wang** [comment]
OK,do you want a basic CNN pre-training model, or a technologically innovative CNN pre-training model, we have proposed an innovative pathological self-supervised CNN model
