### ISSUE TITLE
About MoCo V3 features

### ISSUE THREAD

**Issue by HHHedo** [Xiyue-Wang/TransPath#17]
Hi xiyue,
Thanks for your great work!
When I reproduce your work, in `get_features_mocov3.py `,  I found the MoCo V3 features are generated after the predictor with dimension of 256. I think the feature should be 384-D after the vit-small, and both the head and predictor should be `nn.Identity()`. 
Looking forward to your help!

Best,
Tiancheng

**Comment by Xiyue-Wang** [comment]
Yes, you can try it, it's easy to change, add a sentence of code, but I recommend ctranspath, and many people have proved that it works well

**Comment by HHHedo** [comment]
> Yes, you can try it, it's easy to change, add a sentence of code, but I recommend ctranspath, and many people have proved that it works well

OK, thanks for your quick help!
BTW,  in your paper, are the reported results of MoCo v3 based on the 256-D features? As in my experiments, the performance of these features  is really bad. 
Thanks again!

**Comment by Xiyue-Wang** [comment]
Have you used ctranspath? Are you normalizing these correctly?Please note that the backbone is the same in the paper.By the way, I have changed the feature dimension of vit's mocov3 to 384.

**Comment by HHHedo** [comment]
> Have you used ctranspath? Are you normalizing these correctly?Please note that the backbone is the same in the paper.By the way, I have changed the feature dimension of vit's mocov3 to 384.

I used ctranspth the way in [get_features_CTransPath.py](https://github.com/Xiyue-Wang/TransPath/blob/main/get_features_CTransPath.py), and it performs well. Should I further normalize them?

**Comment by Xiyue-Wang** [comment]
That's no problem, I thought your vit mocov3 input image is not normalized, you try 384 vit, but we rarely use it
